#数据库配置--根据生产环境信息配置
database:
  # 数据库类型 mysql sqlite
  type: mysql
  #数据库名称
  dbName: database_blog
  ip: 127.0.0.1
  port: 3306
  username: root
  password:
  autoMigrate: true
server:
  name: domain_blog
  port: 40051
system:
  #初始化用户 1-初始化 0-不初始化
  initUser : 1
redis:
  #单例模式-0 集群模式-1
  haType: 0
  host: 127.0.0.1
  port: 6379
  password:
  seconds: 5
  # 1-启动 0-不启动
  enable: 1
logger:
  #日志打印方式 file,console
  type: file
  #日志文件名称
  filename: domain_blog.log
  #最大行数
  maxlines: 1000000
  #最大字节数
  maxsize: 524288000
  #是否开启日常切分
  daily: true
  #最大保存天数
  maxdays: 2
  #是否开启切分
  rotate: true
  #日志级别
  level: INFO
  #日志文件路径
  logpath: /home/server/log/go
  #文件权限
  perm: 664
  #开启异步记录
  isAsync: true